on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

name: "Lint, test and build"
run-name: "Linting, testing and building app"

jobs:
  build_test:
    runs-on: ubuntu-latest
    environment: CICD
    strategy:
      matrix:
        node-version: [ 18.x ]

    steps:
      - uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@master
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: |
            ~/.npm
            node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: |
          npm install

      - name: Build
        run: |
          npm run build
          npm run lint
          npm run test

  notification_job:
    runs-on: ubuntu-latest
    environment: CICD
    if: ${{ always() }}
    steps:
      - name: Discord Notification on Failure
        if: ${{ success() }}
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: Ilshidur/action-discord@master
        with:
          args: 'The project {{ EVENT_PAYLOAD.repository.full_name }} (lint, tests) passed the lint and tests.'

      - name: Discord Notification on Failure
        if: ${{ failure() }}
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: Ilshidur/action-discord@master
        with:
          args: 'The project {{ EVENT_PAYLOAD.repository.full_name }} has failed.'
